language: ruby
rvm:
  - 2.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - export CURLOPT_TIMEOUT=60
  - export CURLOPT_CONNECTTIMEOUT=10
  - "export CURLOPT_USERAGENT=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"

install:
  - bundle install

script:
  - bundle exec "jekyll build --drafts"
  - rake test

notifications:
  email: false

branches:
  only:
    - gh-pages
