language: ruby
rvm:
  - 2.1

notifications:
  email: false

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CURLOPT_TIMEOUT=60
    - CURLOPT_CONNECTTIMEOUT=10
    - CURLOPT_USERAGENT="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"

before_install:
  - openssl aes-256-cbc -K $encrypted_174f06e19b8d_key -iv $encrypted_174f06e19b8d_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - chmod 600 .travis/deploy_key
  - eval "$(ssh-agent)"
  - ssh-add .travis/deploy_key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "kingersoll+travis-ci-deploy@gmail.com"

install:
  - bundle install

before_script:
  - git clone -b gh-pages git@github.com:iwantmyname/blog.git _site

script:
  - bundle exec jekyll build

after_success:
  - cd _site
  - touch .nojekyll
  - git add -A
  - git commit -m "jekyll build" -m "https://travis-ci.org/iwantmyname/blog/builds/$TRAVIS_BUILD_ID"
  - git push origin gh-pages
  - cd ..
  - rake test
