language: ruby
rvm:
  - 2.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - export CURLOPT_TIMEOUT=60
  - export CURLOPT_CONNECTTIMEOUT=10

install:
  - bundle install

script:
  - bundle exec "jekyll build --drafts"
  - bundle exec "htmlproof ./_site --verbose"

notifications:
  email: false

branches:
  only:
    - gh-pages
